import type { FeaturedEvent, Venue } from "@/lib/types";

export const fallbackEvents: FeaturedEvent[] = [
  {
    id: "sunset-beats",
    title: "Sunset Beats",
    venue: "Quiosque Maralto",
    date: "Sexta",
    time: "19:30",
    genre: "House e brasilidades",
    price: "R$ 25",
    image:
      "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?auto=format&fit=crop&w=1600&q=88",
    highlight: "DJ convidado, vista para o mar e combo para grupos.",
    mood: "Energia alta",
    distance: "1.8 km",
  },
  {
    id: "samba-da-vila",
    title: "Samba da Vila",
    venue: "Vila Gastrobar",
    date: "Sábado",
    time: "21:00",
    genre: "Samba e pagode",
    price: "Grátis",
    image: "/events/samba-da-vila-real.jpg",
    highlight: "Mesa compartilhada, drinks autorais e lista amiga.",
    mood: "Roda cheia",
    distance: "850 m",
  },
  {
    id: "karaoke-night",
    title: "Karaokê Night",
    venue: "Lagoa Lounge",
    date: "Domingo",
    time: "20:00",
    genre: "Open mic",
    price: "R$ 15",
    image:
      "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1600&q=88",
    highlight: "Ranking da noite, brindes e palco aberto.",
    mood: "Leve e social",
    distance: "2.4 km",
  },
  {
    id: "forro-na-orla",
    title: "Forró na Orla",
    venue: "Deck Itaúna",
    date: "Quinta",
    time: "20:30",
    genre: "Forró e xote",
    price: "R$ 20",
    image: "/events/trio-forro-834x298.jpeg",
    highlight: "Aula aberta no começo da noite e pista livre até tarde.",
    mood: "Dançante",
    distance: "1.2 km",
  },
  {
    id: "rock-lagoon",
    title: "Rock Lagoon",
    venue: "Lagoa Beer House",
    date: "Sábado",
    time: "22:00",
    genre: "Rock ao vivo",
    price: "R$ 30",
    image: "/events/rock-lagoon-real.jpg",
    highlight: "Bandas locais, chope artesanal e área externa na lagoa.",
    mood: "Ao vivo",
    distance: "3.1 km",
  },
  {
    id: "brunch-sunset",
    title: "Brunch Sunset",
    venue: "Casa do Alto",
    date: "Domingo",
    time: "16:00",
    genre: "Sunset e jazz",
    price: "R$ 45",
    image:
      "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1600&q=88",
    highlight: "Fim de tarde com menu especial, jazz e vista panorâmica.",
    mood: "Chill",
    distance: "2.9 km",
  },
  {
    id: "open-decks",
    title: "Open Decks",
    venue: "Wave Club",
    date: "Sexta",
    time: "23:30",
    genre: "Eletrônica",
    price: "R$ 35",
    image:
      "https://images.pexels.com/photos/30640568/pexels-photo-30640568.jpeg?auto=compress&cs=tinysrgb&w=1600",
    highlight: "Line-up rotativo com DJs da região e pista até de madrugada.",
    mood: "Pista cheia",
    distance: "1.6 km",
  },
  {
    id: "comedy-drinks",
    title: "Comedy & Drinks",
    venue: "Beco 22",
    date: "Terça",
    time: "20:00",
    genre: "Stand-up",
    price: "R$ 18",
    image:
      "https://images.pexels.com/photos/10078868/pexels-photo-10078868.jpeg?auto=compress&cs=tinysrgb&w=1600",
    highlight: "Noite de humor com cardápio de drinks autorais.",
    mood: "Leve",
    distance: "650 m",
  },
];

export const fallbackVenues: Venue[] = [
  {
    id: "maralto",
    name: "Quiosque Maralto",
    category: "Praia e música",
    rating: 4.8,
    latitude: -22.9296,
    longitude: -42.5103,
    address: "Orla de Itaúna",
    vibe: "Vista, musica e grupos",
  },
  {
    id: "vila-gastrobar",
    name: "Vila Gastrobar",
    category: "Bar e gastronomia",
    rating: 4.6,
    latitude: -22.9344,
    longitude: -42.4968,
    address: "Centro de Saquarema",
    vibe: "Drinks, samba e jantar",
  },
  {
    id: "lagoa-lounge",
    name: "Lagoa Lounge",
    category: "Lounge e drinks",
    rating: 4.7,
    latitude: -22.9209,
    longitude: -42.5072,
    address: "Lagoa de Saquarema",
    vibe: "Lounge, karaokê e encontro",
  },
  {
    id: "deck-itauna",
    name: "Deck Itaúna",
    category: "Dança e praia",
    rating: 4.5,
    latitude: -22.9312,
    longitude: -42.5148,
    address: "Itaúna",
    vibe: "Forró, pista aberta e orla",
  },
  {
    id: "wave-club",
    name: "Wave Club",
    category: "Club e DJs",
    rating: 4.4,
    latitude: -22.9362,
    longitude: -42.5018,
    address: "Centro",
    vibe: "Eletrônica, pista e madrugada",
  },
];
